Repository csvalpha/amber-api, pull requests merged in 2024-10, with the labels that each got.

#444 Fixed the error CD gives
  .github/workflows/continuous-integration.yml
Labels: status:ready to review

#400 feat(tests): add code coverage reporting
  .github/workflows/continuous-integration.yml
  Gemfile
  Gemfile.lock
  README.md
  app/resources/v1/application_resource.rb
  app/resources/v1/group_resource.rb
  spec/jobs/sentry_job_spec.rb
  spec/requests/v1/activities_controller/ical_spec.rb
  spec/requests/v1/activities_controller/index_spec.rb
  spec/requests/v1/daily_verses_controller/index_spec.rb
  spec/requests/v1/groups_controller/index_spec.rb
  spec/resources/v1/activity_resource_spec.rb
  spec/resources/v1/group_resource_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/retrieve_daily_verse.yml
Labels: status:ready to review, type:feature

#401 refactor(cleanup-registry): use new action
  .github/workflows/cleanup-registry.yml
Labels: status:ready to review, type:enhancement
